In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
"Haan bhaae Hogaya hai change reflect jaan chor dy ab"

In [14]:
X,y = make_regression(n_samples=200, n_features=2, n_informative=2, n_targets=1, noise=50)

In [17]:
X

array([[ 1.29534480e+00,  1.55377554e-01],
       [ 5.45510665e-01, -1.71767767e+00],
       [ 1.94135688e+00,  5.50557584e-01],
       [ 6.65971628e-01,  1.40873749e+00],
       [-8.92859578e-01,  5.27535192e-01],
       [-3.99819797e-01, -4.95495416e-01],
       [-2.34513658e-01, -1.03808876e+00],
       [-3.48374222e-01,  9.76602587e-01],
       [-8.74167892e-02, -1.11841674e+00],
       [ 1.85489768e+00, -1.12084486e+00],
       [-8.24883477e-01,  1.08951950e+00],
       [-1.81058468e+00,  2.27841297e+00],
       [ 1.19457244e+00, -8.11995802e-01],
       [-1.08217957e+00, -9.98812020e-01],
       [ 2.22174745e+00,  9.48689105e-01],
       [ 9.89263006e-01, -4.87377118e-01],
       [ 6.67530595e-01,  2.57878477e-01],
       [ 1.46975182e-02,  7.83214373e-01],
       [ 7.07919507e-01, -1.21673648e+00],
       [ 3.97975239e-01, -7.72193001e-01],
       [ 7.43172617e-01, -3.45020357e-01],
       [-7.66281899e-01,  4.04426908e-01],
       [ 1.47480413e+00, -3.02259732e-01],
       [ 6.

In [18]:
y

array([ 1.07512860e+02,  3.06559988e+01,  6.73051980e+01, -3.05019430e+01,
       -2.97299602e+01, -2.77521972e+01, -4.29653213e+00,  7.64834708e+01,
        1.62663605e+01,  1.15927280e+02, -7.02659843e+00, -9.04190692e+01,
        1.10546794e+02, -7.87855548e+01,  1.79974884e+02,  1.08864840e+02,
       -7.03060942e+00, -1.26880489e+01,  4.06252934e+01,  3.83619189e+01,
       -2.27565626e+01, -7.71805625e+01, -1.87966750e+00,  1.06758047e+01,
       -6.33665199e+01,  1.87768595e+01,  1.33535730e+02,  1.37153685e+01,
       -4.44549493e+00, -3.87571100e+01,  1.27219706e+02,  7.77473668e+01,
        6.87910130e+00,  1.07894446e+02,  1.59597630e+01,  6.45953172e+01,
       -9.46428367e+01,  1.01390211e+02,  1.16101944e+02,  8.91641965e+01,
        8.19490649e+01, -1.22089221e+02, -2.14709029e+01, -6.17714759e+01,
        1.36040847e+02, -4.19481113e+01, -7.16623638e+01,  5.58492306e+01,
       -1.44263715e+00, -1.68472188e+01,  1.66825169e+01,  1.63996607e+01,
       -9.39736376e+01,  

In [15]:
df=pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [16]:
df

feature1  feature2      target
0    1.295345  0.155378  107.512860
1    0.545511 -1.717678   30.655999
2    1.941357  0.550558   67.305198
3    0.665972  1.408737  -30.501943
4   -0.892860  0.527535  -29.729960
..        ...       ...         ...
195  0.927562 -0.299500   48.401647
196  1.634257  0.082144   75.040818
197  0.997058 -0.149980   57.296753
198 -0.425894  0.569784  -18.597350
199 -1.468229  0.549979  -71.672116

[200 rows x 3 columns]

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [21]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [22]:
model.coef_

array([67.26684798, 22.61507465])

In [23]:
model.intercept_

5.992469631871582

In [26]:
y_predict=model.predict(X_test)

In [28]:
print(f'MSE: {mean_squared_error(y_test,y_predict)}')
print(f'MAE: {mean_absolute_error(y_test,y_predict)}')
print(f'RMSE: {np.sqrt(mean_squared_error(y_test,y_predict))}')
print(f'R2 score: {r2_score(y_test,y_predict)}')

MSE: 2365.693012724084
MAE: 38.0638186834867
RMSE: 48.63839031797911
R2 score: 0.6411139601073128


### MLR Using Sklearn Class

In [30]:
from sklearn.datasets import load_diabetes

In [31]:
df=load_diabetes()

In [35]:
X=df['data']

In [36]:
X.shape

(442, 10)

In [38]:
y=df['target']

In [39]:
y.shape

(442,)

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [44]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [45]:
lr=LinearRegression()
lr.fit(X_train,y_train)
y_predict=lr.predict(X_test)

In [46]:
y_predict

array([156.53492102, 249.44105415, 102.38092855,  38.14034537,
       142.96451854,  92.36136935, 129.52877084, 157.57576276,
        44.86707791, 154.89232078, 158.06243032,  54.58735952,
       201.03170559, 237.19838689,  76.7045112 , 158.35759287,
       172.89221631, 180.88296657, 183.09585807, 192.67913403,
        79.76200808, 146.570457  , 123.19958848, 148.08194102,
       167.01668198, 155.56531359,  91.60120891, 210.61425038,
        86.48448998, 198.8729646 , 208.77193341,  53.76737842,
       178.00440374,  58.643521  , 153.76045447, 207.01183778,
       169.01904766, 278.24561767, 123.34783705, 107.69444352,
       100.27768925, 181.81190698, 255.1895647 , 119.24474145,
       218.71806599, 176.57180042, 114.44603524,  98.46050711,
       252.95864299, 180.1905315 , 157.36769158, 123.99701567,
       163.60531333, 106.88299229, 189.82640272, 214.55737866,
       185.77273608, 141.59310323, 287.3027544 , 159.57524332,
       129.78259488, 216.56612944, 117.27540473, 121.88

In [47]:
lr.coef_

array([ -61.2414266 , -231.35781482,  506.64659567,  309.97240101,
       -860.86855359,  537.66779628,   88.40196997,  176.3544726 ,
        744.703884  ,  105.29197386])

In [48]:
lr.intercept_

151.10524426252516

In [50]:
r2_score(y_test,y_predict)

0.5891627868789857

### MLR From Scratch Class

In [64]:
class MLR:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)
        
        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    
    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred
        

In [70]:
mlr=MLR()
mlr.fit(X_train,y_train)
y_predict=mlr.predict(X_test)

In [66]:
mlr.coef_

array([ -61.2414266 , -231.35781482,  506.64659567,  309.97240101,
       -860.86855359,  537.66779628,   88.40196997,  176.3544726 ,
        744.703884  ,  105.29197386])

In [67]:
mlr.intercept_

151.10524426252516

In [68]:
lr.coef_

array([ -61.2414266 , -231.35781482,  506.64659567,  309.97240101,
       -860.86855359,  537.66779628,   88.40196997,  176.3544726 ,
        744.703884  ,  105.29197386])

In [69]:
lr.intercept_

151.10524426252516

In [72]:
r2_score(y_test,y_predict)

0.5891627868789855